# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-QvLMiEVM_QdP-g2ESKYUfm03PtOZg2J
"""

a = int(input())
if a%400==0:
  print("да")
else:
  if a%100==0:
   print("нет")
  else:
    if a%4==0:
      print("да")
    else:
      print("нет")