# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sfO6y655XJZEDLmPGx41cIClNg7QX0RC
"""

year = int(input())

if year % 400 == 0:
    print('да')
elif year % 100 == 0:
    print('нет')
elif year % 4 == 0:
    print('да')
else:
    print('нет')